---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: ensure latest apache is installed
    apt:
      name: apache2
      state: latest
  - name: ensure apache is running
    service:
      name: apache2
      state: started